DROP TABLE IF EXISTS kafka;

CREATE TABLE kafka (
   id SERIAL PRIMARY KEY,
   value text
);

SELECT count(*) FROM KAFKA

BEGIN TRANSACTION;
    INSERT INTO KAFKA (value) VALUES ('seed') RETURNING *;
COMMIT;

SELECT * FROM KAFKA